[package]
name = "rdocx"
description = "High-level API for reading, writing, and converting DOCX documents"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[package.metadata.release]
shared-version = "workspace"
tag-name = "v{{version}}"

[features]
default = ["system-fonts"]
system-fonts = ["oxml-layout/system-fonts", "rdocx-layout/system-fonts"]

[dependencies]
oxml-chart = { workspace = true }
oxml-core = { workspace = true }
oxml-drawing = { workspace = true }
oxml-layout = { workspace = true, default-features = false }
oxml-media = { workspace = true }
oxml-opc = { workspace = true }
oxml-pdf = { workspace = true, default-features = false }
oxml-sml = { workspace = true }
quick-xml = { workspace = true }
rdocx-oxml = { workspace = true }
rdocx-layout = { workspace = true, default-features = false }
rdocx-html = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
rpptx = { workspace = true, features = ["default-template", "render"] }
