[package]
name = "rpptx"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["pptx", "powerpoint", "ooxml", "presentation"]
categories = ["parser-implementations", "text-processing"]
publish = false

[features]
default = ["default-template"]
default-template = []

[dependencies]
oxml-layout.workspace = true
oxml-media.workspace = true
oxml-opc.workspace = true
rpptx-oxml.workspace = true
thiserror.workspace = true

[dev-dependencies]
oxml-drawing.workspace = true
oxml-layout.workspace = true
oxml-pdf.workspace = true
rpptx-layout.workspace = true
rpptx-render.workspace = true
