#!/usr/bin/env python3
"""Generate the Codex skill adapters under `.agents/skills/`.

`.claude/commands/*.md` and `.claude/skills/*.md` stay canonical. Codex
discovers checked-in skills under `.agents/skills/<name>/SKILL.md`, so this
writes one thin adapter per source that points back at the canonical file
rather than duplicating it. A copy would drift, and a drifted copy is worse
than no Codex support, because the two agents would then be following different
rules while believing they agreed.

`--check` is a gate. `/verify` runs it, so an edit to a command that forgets to
regenerate fails the build rather than going unnoticed.

Usage:
    python3 scripts/sync_agent_skills.py
    python3 scripts/sync_agent_skills.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

GENERATED_MARKER = "<!-- Generated by scripts/sync_agent_skills.py. Do not edit. -->"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

# Words that look wrong in title case. Extend deliberately.
ACRONYMS = {"hld", "api", "xml", "ooxml", "pdf"}


@dataclass(frozen=True)
class SourceSkill:
    name: str
    description: str
    source: str
    source_sha256: str
    manual_only: bool


def repo_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        check=True,
        capture_output=True,
        text=True,
    )
    return Path(result.stdout.strip())


def split_frontmatter(text: str, source: Path) -> dict[str, str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{source}: missing YAML frontmatter")
    try:
        end = lines[1:].index("---") + 1
    except ValueError as error:
        raise ValueError(f"{source}: unterminated YAML frontmatter") from error

    metadata: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"{source}: unsupported frontmatter line: {line}")
        key, value = line.split(":", 1)
        metadata[key.strip()] = value.strip().strip('"').strip("'")
    return metadata


def load_sources(root: Path) -> list[SourceSkill]:
    # A command is an explicit invocation, so Codex must not fire it on its own
    # guess. A flat skill is reference material and is fine to consult.
    candidates = [(p, True) for p in sorted((root / ".claude/commands").glob("*.md"))]
    candidates += [(p, False) for p in sorted((root / ".claude/skills").glob("*.md"))]

    skills: list[SourceSkill] = []
    seen: set[str] = set()
    for path, manual_only in candidates:
        metadata = split_frontmatter(path.read_text(encoding="utf-8"), path)
        name = metadata.get("name", path.stem)
        description = metadata.get("description", "").strip()
        if not NAME_RE.fullmatch(name):
            raise ValueError(f"{path}: invalid skill name {name!r}")
        if not description:
            raise ValueError(f"{path}: a description is required in the frontmatter")
        if name in seen:
            raise ValueError(f"duplicate generated skill name: {name}")
        seen.add(name)
        skills.append(
            SourceSkill(
                name=name,
                description=description,
                source=path.relative_to(root).as_posix(),
                source_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                manual_only=manual_only,
            )
        )
    if not skills:
        raise ValueError("no sources found under .claude/commands or .claude/skills")
    return skills


def display_name(name: str) -> str:
    return " ".join(
        part.upper() if part in ACRONYMS else part.title() for part in name.split("-")
    )


def short_description(description: str) -> str:
    compact = " ".join(description.split()).rstrip(".")
    if len(compact) > 64:
        compact = compact[:61].rstrip() + "..."
    return compact


def render_skill(skill: SourceSkill) -> str:
    return (
        "---\n"
        f"name: {skill.name}\n"
        f"description: {json.dumps(skill.description)}\n"
        "---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"Canonical source: `{skill.source}`.\n\n"
        f"Source SHA-256: `{skill.source_sha256}`.\n\n"
        "Read the canonical source in full before acting, and follow it with "
        "whatever tools this host provides. Treat any invocation arguments as "
        "arguments to that workflow. Where it names another slash command, "
        "follow the repository skill of the same name. Where it says to ask "
        "with `AskUserQuestion`, ask through this host's own question "
        "mechanism. `.claude/WORKFLOW.md` wins on any process question. Do not "
        "edit this generated adapter.\n"
    )


def render_openai_yaml(skill: SourceSkill) -> str:
    return (
        "interface:\n"
        f"  display_name: {json.dumps(display_name(skill.name))}\n"
        f"  short_description: {json.dumps(short_description(skill.description))}\n"
        f"  default_prompt: {json.dumps(f'Use ${skill.name} to follow the repository workflow.')}\n"
        "policy:\n"
        f"  allow_implicit_invocation: {'false' if skill.manual_only else 'true'}\n"
    )


def expected_files(root: Path) -> dict[Path, str]:
    output_root = root / ".agents/skills"
    expected: dict[Path, str] = {}
    for skill in load_sources(root):
        folder = output_root / skill.name
        expected[folder / "SKILL.md"] = render_skill(skill)
        expected[folder / "agents/openai.yaml"] = render_openai_yaml(skill)
    return expected


def generated_skill_dirs(output_root: Path) -> set[Path]:
    """Directories this script owns. A hand-written skill is left alone."""
    if not output_root.exists():
        return set()
    return {
        f.parent
        for f in output_root.glob("*/SKILL.md")
        if GENERATED_MARKER in f.read_text(encoding="utf-8", errors="ignore")
    }


def check(root: Path, expected: dict[Path, str]) -> int:
    failures: list[str] = []
    expected_dirs = {p.parent for p in expected if p.name == "SKILL.md"}
    for stale in sorted(generated_skill_dirs(root / ".agents/skills") - expected_dirs):
        failures.append(f"stale generated skill: {stale.relative_to(root)}")
    for path, wanted in sorted(expected.items()):
        if not path.exists():
            failures.append(f"missing: {path.relative_to(root)}")
        elif path.read_text(encoding="utf-8") != wanted:
            failures.append(f"drifted: {path.relative_to(root)}")

    if failures:
        for f in failures:
            print(f"sync_agent_skills: {f}", file=sys.stderr)
        print(
            "sync_agent_skills: run `python3 scripts/sync_agent_skills.py`",
            file=sys.stderr,
        )
        return 1
    print(f"sync_agent_skills: {len(expected) // 2} skills in sync")
    return 0


def write(root: Path, expected: dict[Path, str]) -> int:
    expected_dirs = {p.parent for p in expected if p.name == "SKILL.md"}
    for stale in sorted(generated_skill_dirs(root / ".agents/skills") - expected_dirs):
        shutil.rmtree(stale)
    for path, content in sorted(expected.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"sync_agent_skills: generated {len(expected) // 2} skills")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail when adapters drifted")
    args = ap.parse_args()
    try:
        root = repo_root()
        expected = expected_files(root)
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        print(f"sync_agent_skills: {error}", file=sys.stderr)
        return 2
    return check(root, expected) if args.check else write(root, expected)


if __name__ == "__main__":
    raise SystemExit(main())
