[package]
name = "rpptx-py"
description = "Python bindings for rpptx"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.release]
shared-version = "workspace"
tag-name = "v{{version}}"
pre-release-replacements = [
    { file = "pyproject.toml", search = 'version = "[^"]+"', replace = 'version = "{{version}}"', exactly = 1 },
]

[lib]
name = "_rpptx"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
oxml-py-support = { workspace = true }
pyo3 = { workspace = true }
rpptx = { workspace = true, features = ["system-fonts"] }
smallvec = { workspace = true }
